#!/bin/csh -f

clear
printf "\n\nRemoving all old logfiles\!\!\!\!\nHit enter to continue or <ctrl c> to quit\n\n"
set x = $<

rm ../log/*.log

./run_modelsim top SDR_8BIT
./run_modelsim top SDR_16BIT
./run_modelsim top SDR_32BIT

./run_modelsim core SDR_8BIT
./run_modelsim core SDR_16BIT
./run_modelsim core SDR_32BIT

clear

./regression_analysis
